### PR TITLE
some changes in the landing page

### PR DESCRIPTION
**Pull request by kulendu**
### Added a clock (using vanilla JS) so to make the page more visually appealing, also made some changes in the background color

### CODE REVIEW

**Comment by Rishikesh-12** [comment]
Please do not make any changes to `README.md`
Also, your pull request has a merge conflict.

It's best that you make a new pull request.

**Comment by kulendu** [comment]
Yeah sure!
And @Rishikesh-12 plz check I have made another PR, kindly review it

**Comment by Rishikesh-12** [comment]
what is the new pr number?

**Comment by kulendu** [comment]
I created a new PR

> what is the new pr number?

#398.... Here it is 👍

**Pull request closed without merging**
