### PR TITLE
queue implementation

### PR DESCRIPTION
**Pull request by rijusougata13**

### CODE REVIEW

**Comment by navneetsn18** [comment]
@rijusougata13 Can you please explain me what have you done in the files other than the first c file

**Comment by rijusougata13** [comment]
> @rijusougata13 Can you please explain me what have you done in the files other than the first c file

can you tell me where you get the .c file ? because the main file is .py file .in that python file i have wriiten the code other than there is audio.mp3 file which is genrated audio file..in that python file you just have to enter the pdf file location

**Comment by navneetsn18** [comment]
Screenshot 2020-10-10 at 6 05 06 PM
@rijusougata13 Please check the file changes and read the name of your first file. There is a description available when you create a PR you can specify there what is your program about.

**Comment by navneetsn18** [comment]
You can see your name and the file name on the above screenshot and also the commit name. It was mentioned Queue implementation so we thought that you are creating a program for queue implementation. So please note these thing for the next time when you create a PR.

**Comment by rijusougata13** [comment]
oh ok i found the mistake i am closing this pr

**Pull request closed without merging**
