### PR TITLE
Bus Reservation System in C++

### PR DESCRIPTION
**Pull request by HarshiniR4**

### CODE REVIEW

**Comment by deadline007** [comment]
what is the issue?

**Comment by HarshiniR4** [comment]
Sorry... It was by mistake.. the actual issue is https://github.com/Rishikesh-12/HacktoberFest2020/pull/305

**Comment by deadline007** [comment]
Okay I have merged the pull request number 305

**Comment by HarshiniR4** [comment]
Thanks!

**Pull request closed without merging**
