### PR TITLE
Tree traversal python notebook

### PR DESCRIPTION
**Pull request by navneetsn18**
Tree traversal like Inorder, Preorder and Postorder.

### CODE REVIEW

**Comment by Rishikesh-12** [comment]
@navneetsn18 Kindly provide a discription

**Review by Rishikesh-12 — CHANGES_REQUESTED** [review]
Kindly provide description

**Comment by navneetsn18** [comment]
@Rishikesh-12 can u please help me on discord..

**Review by Rishikesh-12 — APPROVED** [review]

**Comment by Rishikesh-12** [comment]
@all-contributors please add @navneetsn18 for code doc review maintenance

**Pull request merged**
