### PR TITLE
Added Palindrome No. Check

### PR DESCRIPTION
**Pull request by ankitamandal07**

### CODE REVIEW

**Review by Rishikesh-12 — APPROVED** [review]
Great

**Comment by Rishikesh-12** [comment]
@all-contributions please add @ankitamandal07 for code

**Comment by Rishikesh-12** [comment]
@all-contributions please add @ankitamandal07 for code

**Comment by ankitamandal07** [comment]
@all-contributors please add @ankitamandal07 for 💻

**Pull request merged**
