### PR TITLE
Fixed a Typo

### PR DESCRIPTION
**Pull request by Siddhant-K-code**

### CODE REVIEW

**Review by Rishikesh-12 — APPROVED** [review]
Thanks

**Comment by Rishikesh-12** [comment]
@all-contributors please add @Siddhant-K-code for code

**Comment by Siddhant-K-code** [comment]
@Rishikesh-12 check my other PRs too regarding Searching and Sorting

**Comment by Rishikesh-12** [comment]
what is the pr number?

**Comment by Siddhant-K-code** [comment]
#58

**Pull request merged**
