### PR TITLE
Added a Web_Page

### PR DESCRIPTION
**Pull request by kalyani489**
A Web Page created using HTML, CSS and Js

### CODE REVIEW

**Comment by navneetsn18** [comment]
I could not find any code in your PR. I think you have just created a folder. Please make the necessary changes and create a new PR.

**Comment by deadline007** [comment]
@kalyani489 kindly update the pull request or make a new one.

**Comment by kalyani489** [comment]
Sure
I'll update my pull request

**Comment by deadline007** [comment]
Okay great!

**Comment by Rishikesh-12** [comment]
Hello, @kalyani489 since there is no change to this pull request we are closing this pull request. If you have any doubts kindly open a new issue mentioning me and this pull request number.

**Pull request closed without merging**
