### PR TITLE
Create helloworld.java

### PR DESCRIPTION
**Pull request by navneetsn1809**
Trying action.yml

### CODE REVIEW

**Review by Rishikesh-12 — COMMENTED** [review]
Okay

**Comment by navneetsn18** [comment]
@all-contributors add @navneetsn18 for documentation

**Comment by navneetsn18** [comment]
@all-contributors please add @navneetsn1809 for code

**Comment by navneetsn18** [comment]
@all-contributors please add @navneetsn18 for mentoring , content

**Pull request merged**
