### PR TITLE
Added Printing Pattern

### PR DESCRIPTION
**Pull request by Abhishek765**

### CODE REVIEW

**Review by Rishikesh-12 — CHANGES_REQUESTED** [review]
please add line 1 and 2 again

```
1 pattern printing
2 print any pattern you like.
```

**Review by Abhishek765 — COMMENTED** [review]
Added Line 1 and 2

**Review by deadline007 — APPROVED** [review]
Great Work

**Comment by deadline007** [comment]
@all-contributors please add @Abhishek765 for code

**Pull request merged**
