### PR TITLE
Added Bootstrap project

### PR DESCRIPTION
**Pull request by insane-abhinav**
Added Bootstrap form project and made GST calculator user input..

### CODE REVIEW

**Comment by insane-abhinav** [comment]
Sorry for delay to resolve conflicts because its my first time on Github

**Comment by deadline007** [comment]
> Sorry for delay to resolve conflicts because its my first time on Github

no problem

**Review by deadline007 — APPROVED** [review]
@Rishikesh-12 , I have approved only the Bootstrap/forms.html file.

Kindly merge the pr, after review.

**Review by Rishikesh-12 — APPROVED** [review]
Okay, Happy with your review.

**Comment by Rishikesh-12** [comment]
@insane-abhinav Sory we won't be able to merge this pull request because of a merge conflict.
If you can make a new pull request with `Bootstrap/forms.html` file, we will be very happy to merge it.

**Comment by insane-abhinav** [comment]
sure!

**Comment by Rishikesh-12** [comment]
@insane-abhinav please mention the pr number of your new pull request here

**Comment by insane-abhinav** [comment]
Conflicts resolved at PR #271

**Comment by navneetsn18** [comment]
As pr 271 is approved so i am closing this pr.

**Pull request closed without merging**
