### PR TITLE
Added Some CP Problems

### PR DESCRIPTION
**Pull request by AdityaSriram09**
@Rishikesh-12  please review and merge

### CODE REVIEW

**Review by deadline007 — COMMENTED** [review]
Do this Programs work?

**Comment by navneetsn18** [comment]
@AdityaSriram09 please make the necessary changes required to execute these programs. As I think the extension for these files should be .c instead of .cxx

**Comment by AdityaSriram09** [comment]
No they are in CPP and they work fine

**Comment by deadline007** [comment]
Okay.

**Review by deadline007 — APPROVED** [review]

**Comment by deadline007** [comment]
@all-contributors please add @AdityaSriram09  for code

**Pull request merged**
